services:
  docker-monitor:
    image: ghcr.io/aldarondo/docker-monitor:latest
    container_name: docker-monitor
    restart: unless-stopped
    environment:
      - GH_PAT=${GH_PAT}
      - USE_DOCKER_SOCKET=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    command: sh -c "python monitor.py 2>&1 | tee -a /app/logs/app.log"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
